#  _______  _______  _______                    _______           _______ 
# / ___   )(  ____ \(  ____ )|\     /||\     /|(  ____ )|\     /|(  ____ \
# \/   )  || (    \/| (    )|| )   ( |( \   / )| (    )|| )   ( || (    \/
#     /   )| (__    | (____)|| (___) | \ (_) / | (____)|| |   | || (_____ 
#    /   / |  __)   |  _____)|  ___  |  \   /  |     __)| |   | |(_____  )
#   /   /  | (      | (      | (   ) |   ) (   | (\ (   | |   | |      ) |
#  /   (_/\| (____/\| )      | )   ( |   | |   | ) \ \__| (___) |/\____) |
# (_______/(_______/|/       |/     \|   \_/   |/   \__/(_______)\_______)

# Enables or disables the update checker.
UpdateChecker: true

# Enables giving players spells via permissions. Ops will automatically have access to all spells.
OpKnowledge: false

# The colour code of the error messages
ErrorColour: 4

# ######### #
# Balancing #
# ######### #

# Casting mana multiplier where 5 is default. Change only if you think the mana costs are over/under powered.
# Only use positive numbers. 0 will drain no mana.
# See spells.yml to change each individual spell's mana cost
ManaMultiplier: 5

# The rate of one mana regeneration in ticks. 30 by default.
# 20 ticks is one second
ManaRegen: 30

# The balancing number for level progression. 
# Complicated equation: (Level * LevelBalance) + (Level * Level + 100)
# The equation makes it so that when you are a higher level you require exponentially more XP to levelup.
# i.e. Level 1 will require 180 xp while level 2 will require 264 xp and level 3 will require 379 xp
LevelBalance: 80

# Whether or not a sound should be played when the player levels up
Levelup-Sound: true


# ######## #
# Crafting #
# ######## #


# Configuration for custom recipes. 
# If set to false, all custom recipes (except the wand) will be disabled
Disable-Recipes: false

# Disables the ability to craft spells with items on a bookshelf
Disable-Spell-Crafting: false

# Disables the wand's recipe. It can still be obtained with a BuyWand sign
Disable-Wand-Recipe: false

# The item id of the wand
Wand-ID: 280

# Makes you earn spells when you levelup
Levelup-Spells: false


# ############ #
# Side Effects #
# ############ #


# The configuration for Side Effects
Enable-Side-Effects: true

# The chance for side effects to occure. 
# This number is multiplied by the player's level and the chance is once in that number.
# If set below 1, it will default to 1.
Side-Effect-Chance: 3